application: hoosbus
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /.*
  script: main.py
  
admin_console:
  pages:
  - name: My Console
    url: /admin/interactive
  - name: My Memcache
    url: /admin/memcache
  - name: My Inbound Mail
    url: /admin/inboundmail