application: hoosbus2
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

libraries:
- name: lxml
  version: latest

inbound_services:
- warmup

handlers:
- url: /api/v1/.*
  script: app.api_v1.application
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
# - url: /admin
#   script: app.admin.application
#   login: admin

- url: /.*
  script: app.main.application